(define (problem knights8x8)
  (:domain knights-tour)
  (:objects 
     a1  b1  c1  d1  e1  f1  g1  h1  
     a2  b2  c2  d2  e2  f2  g2  h2  
     a3  b3  c3  d3  e3  f3  g3  h3  
     a4  b4  c4  d4  e4  f4  g4  h4  
     a5  b5  c5  d5  e5  f5  g5  h5  
     a6  b6  c6  d6  e6  f6  g6  h6  
     a7  b7  c7  d7  e7  f7  g7  h7  
     a8  b8  c8  d8  e8  f8  g8  h8  
  )
  (:init 
    (NEIGHBOUR a1 c2)
    (NEIGHBOUR a1 b3)
    (NEIGHBOUR b1 a3)
    (NEIGHBOUR b1 d2)
    (NEIGHBOUR b1 c3)
    (NEIGHBOUR c1 a2)
    (NEIGHBOUR c1 b3)
    (NEIGHBOUR c1 e2)
    (NEIGHBOUR c1 d3)
    (NEIGHBOUR d1 b2)
    (NEIGHBOUR d1 c3)
    (NEIGHBOUR d1 f2)
    (NEIGHBOUR d1 e3)
    (NEIGHBOUR e1 c2)
    (NEIGHBOUR e1 d3)
    (NEIGHBOUR e1 g2)
    (NEIGHBOUR e1 f3)
    (NEIGHBOUR f1 d2)
    (NEIGHBOUR f1 e3)
    (NEIGHBOUR f1 h2)
    (NEIGHBOUR f1 g3)
    (NEIGHBOUR g1 e2)
    (NEIGHBOUR g1 f3)
    (NEIGHBOUR g1 h3)
    (NEIGHBOUR h1 f2)
    (NEIGHBOUR h1 g3)
    (NEIGHBOUR a2 c1)
    (NEIGHBOUR a2 c3)
    (NEIGHBOUR a2 b4)
    (NEIGHBOUR b2 a4)
    (NEIGHBOUR b2 d1)
    (NEIGHBOUR b2 d3)
    (NEIGHBOUR b2 c4)
    (NEIGHBOUR c2 a1)
    (NEIGHBOUR c2 a3)
    (NEIGHBOUR c2 b4)
    (NEIGHBOUR c2 e1)
    (NEIGHBOUR c2 e3)
    (NEIGHBOUR c2 d4)
    (NEIGHBOUR d2 b1)
    (NEIGHBOUR d2 b3)
    (NEIGHBOUR d2 c4)
    (NEIGHBOUR d2 f1)
    (NEIGHBOUR d2 f3)
    (NEIGHBOUR d2 e4)
    (NEIGHBOUR e2 c1)
    (NEIGHBOUR e2 c3)
    (NEIGHBOUR e2 d4)
    (NEIGHBOUR e2 g1)
    (NEIGHBOUR e2 g3)
    (NEIGHBOUR e2 f4)
    (NEIGHBOUR f2 d1)
    (NEIGHBOUR f2 d3)
    (NEIGHBOUR f2 e4)
    (NEIGHBOUR f2 h1)
    (NEIGHBOUR f2 h3)
    (NEIGHBOUR f2 g4)
    (NEIGHBOUR g2 e1)
    (NEIGHBOUR g2 e3)
    (NEIGHBOUR g2 f4)
    (NEIGHBOUR g2 h4)
    (NEIGHBOUR h2 f1)
    (NEIGHBOUR h2 f3)
    (NEIGHBOUR h2 g4)
    (NEIGHBOUR a3 c2)
    (NEIGHBOUR a3 c4)
    (NEIGHBOUR a3 b5)
    (NEIGHBOUR a3 b1)
    (NEIGHBOUR b3 a5)
    (NEIGHBOUR b3 a1)
    (NEIGHBOUR b3 d2)
    (NEIGHBOUR b3 d4)
    (NEIGHBOUR b3 c5)
    (NEIGHBOUR b3 c1)
    (NEIGHBOUR c3 a2)
    (NEIGHBOUR c3 a4)
    (NEIGHBOUR c3 b5)
    (NEIGHBOUR c3 b1)
    (NEIGHBOUR c3 e2)
    (NEIGHBOUR c3 e4)
    (NEIGHBOUR c3 d5)
    (NEIGHBOUR c3 d1)
    (NEIGHBOUR d3 b2)
    (NEIGHBOUR d3 b4)
    (NEIGHBOUR d3 c5)
    (NEIGHBOUR d3 c1)
    (NEIGHBOUR d3 f2)
    (NEIGHBOUR d3 f4)
    (NEIGHBOUR d3 e5)
    (NEIGHBOUR d3 e1)
    (NEIGHBOUR e3 c2)
    (NEIGHBOUR e3 c4)
    (NEIGHBOUR e3 d5)
    (NEIGHBOUR e3 d1)
    (NEIGHBOUR e3 g2)
    (NEIGHBOUR e3 g4)
    (NEIGHBOUR e3 f5)
    (NEIGHBOUR e3 f1)
    (NEIGHBOUR f3 d2)
    (NEIGHBOUR f3 d4)
    (NEIGHBOUR f3 e5)
    (NEIGHBOUR f3 e1)
    (NEIGHBOUR f3 h2)
    (NEIGHBOUR f3 h4)
    (NEIGHBOUR f3 g5)
    (NEIGHBOUR f3 g1)
    (NEIGHBOUR g3 e2)
    (NEIGHBOUR g3 e4)
    (NEIGHBOUR g3 f5)
    (NEIGHBOUR g3 f1)
    (NEIGHBOUR g3 h5)
    (NEIGHBOUR g3 h1)
    (NEIGHBOUR h3 f2)
    (NEIGHBOUR h3 f4)
    (NEIGHBOUR h3 g5)
    (NEIGHBOUR h3 g1)
    (NEIGHBOUR a4 c3)
    (NEIGHBOUR a4 c5)
    (NEIGHBOUR a4 b6)
    (NEIGHBOUR a4 b2)
    (NEIGHBOUR b4 a6)
    (NEIGHBOUR b4 a2)
    (NEIGHBOUR b4 d3)
    (NEIGHBOUR b4 d5)
    (NEIGHBOUR b4 c6)
    (NEIGHBOUR b4 c2)
    (NEIGHBOUR c4 a3)
    (NEIGHBOUR c4 a5)
    (NEIGHBOUR c4 b6)
    (NEIGHBOUR c4 b2)
    (NEIGHBOUR c4 e3)
    (NEIGHBOUR c4 e5)
    (NEIGHBOUR c4 d6)
    (NEIGHBOUR c4 d2)
    (NEIGHBOUR d4 b3)
    (NEIGHBOUR d4 b5)
    (NEIGHBOUR d4 c6)
    (NEIGHBOUR d4 c2)
    (NEIGHBOUR d4 f3)
    (NEIGHBOUR d4 f5)
    (NEIGHBOUR d4 e6)
    (NEIGHBOUR d4 e2)
    (NEIGHBOUR e4 c3)
    (NEIGHBOUR e4 c5)
    (NEIGHBOUR e4 d6)
    (NEIGHBOUR e4 d2)
    (NEIGHBOUR e4 g3)
    (NEIGHBOUR e4 g5)
    (NEIGHBOUR e4 f6)
    (NEIGHBOUR e4 f2)
    (NEIGHBOUR f4 d3)
    (NEIGHBOUR f4 d5)
    (NEIGHBOUR f4 e6)
    (NEIGHBOUR f4 e2)
    (NEIGHBOUR f4 h3)
    (NEIGHBOUR f4 h5)
    (NEIGHBOUR f4 g6)
    (NEIGHBOUR f4 g2)
    (NEIGHBOUR g4 e3)
    (NEIGHBOUR g4 e5)
    (NEIGHBOUR g4 f6)
    (NEIGHBOUR g4 f2)
    (NEIGHBOUR g4 h6)
    (NEIGHBOUR g4 h2)
    (NEIGHBOUR h4 f3)
    (NEIGHBOUR h4 f5)
    (NEIGHBOUR h4 g6)
    (NEIGHBOUR h4 g2)
    (NEIGHBOUR a5 c4)
    (NEIGHBOUR a5 c6)
    (NEIGHBOUR a5 b7)
    (NEIGHBOUR a5 b3)
    (NEIGHBOUR b5 a7)
    (NEIGHBOUR b5 a3)
    (NEIGHBOUR b5 d4)
    (NEIGHBOUR b5 d6)
    (NEIGHBOUR b5 c7)
    (NEIGHBOUR b5 c3)
    (NEIGHBOUR c5 a4)
    (NEIGHBOUR c5 a6)
    (NEIGHBOUR c5 b7)
    (NEIGHBOUR c5 b3)
    (NEIGHBOUR c5 e4)
    (NEIGHBOUR c5 e6)
    (NEIGHBOUR c5 d7)
    (NEIGHBOUR c5 d3)
    (NEIGHBOUR d5 b4)
    (NEIGHBOUR d5 b6)
    (NEIGHBOUR d5 c7)
    (NEIGHBOUR d5 c3)
    (NEIGHBOUR d5 f4)
    (NEIGHBOUR d5 f6)
    (NEIGHBOUR d5 e7)
    (NEIGHBOUR d5 e3)
    (NEIGHBOUR e5 c4)
    (NEIGHBOUR e5 c6)
    (NEIGHBOUR e5 d7)
    (NEIGHBOUR e5 d3)
    (NEIGHBOUR e5 g4)
    (NEIGHBOUR e5 g6)
    (NEIGHBOUR e5 f7)
    (NEIGHBOUR e5 f3)
    (NEIGHBOUR f5 d4)
    (NEIGHBOUR f5 d6)
    (NEIGHBOUR f5 e7)
    (NEIGHBOUR f5 e3)
    (NEIGHBOUR f5 h4)
    (NEIGHBOUR f5 h6)
    (NEIGHBOUR f5 g7)
    (NEIGHBOUR f5 g3)
    (NEIGHBOUR g5 e4)
    (NEIGHBOUR g5 e6)
    (NEIGHBOUR g5 f7)
    (NEIGHBOUR g5 f3)
    (NEIGHBOUR g5 h7)
    (NEIGHBOUR g5 h3)
    (NEIGHBOUR h5 f4)
    (NEIGHBOUR h5 f6)
    (NEIGHBOUR h5 g7)
    (NEIGHBOUR h5 g3)
    (NEIGHBOUR a6 c5)
    (NEIGHBOUR a6 c7)
    (NEIGHBOUR a6 b8)
    (NEIGHBOUR a6 b4)
    (NEIGHBOUR b6 a8)
    (NEIGHBOUR b6 a4)
    (NEIGHBOUR b6 d5)
    (NEIGHBOUR b6 d7)
    (NEIGHBOUR b6 c8)
    (NEIGHBOUR b6 c4)
    (NEIGHBOUR c6 a5)
    (NEIGHBOUR c6 a7)
    (NEIGHBOUR c6 b8)
    (NEIGHBOUR c6 b4)
    (NEIGHBOUR c6 e5)
    (NEIGHBOUR c6 e7)
    (NEIGHBOUR c6 d8)
    (NEIGHBOUR c6 d4)
    (NEIGHBOUR d6 b5)
    (NEIGHBOUR d6 b7)
    (NEIGHBOUR d6 c8)
    (NEIGHBOUR d6 c4)
    (NEIGHBOUR d6 f5)
    (NEIGHBOUR d6 f7)
    (NEIGHBOUR d6 e8)
    (NEIGHBOUR d6 e4)
    (NEIGHBOUR e6 c5)
    (NEIGHBOUR e6 c7)
    (NEIGHBOUR e6 d8)
    (NEIGHBOUR e6 d4)
    (NEIGHBOUR e6 g5)
    (NEIGHBOUR e6 g7)
    (NEIGHBOUR e6 f8)
    (NEIGHBOUR e6 f4)
    (NEIGHBOUR f6 d5)
    (NEIGHBOUR f6 d7)
    (NEIGHBOUR f6 e8)
    (NEIGHBOUR f6 e4)
    (NEIGHBOUR f6 h5)
    (NEIGHBOUR f6 h7)
    (NEIGHBOUR f6 g8)
    (NEIGHBOUR f6 g4)
    (NEIGHBOUR g6 e5)
    (NEIGHBOUR g6 e7)
    (NEIGHBOUR g6 f8)
    (NEIGHBOUR g6 f4)
    (NEIGHBOUR g6 h8)
    (NEIGHBOUR g6 h4)
    (NEIGHBOUR h6 f5)
    (NEIGHBOUR h6 f7)
    (NEIGHBOUR h6 g8)
    (NEIGHBOUR h6 g4)
    (NEIGHBOUR a7 c6)
    (NEIGHBOUR a7 c8)
    (NEIGHBOUR a7 b5)
    (NEIGHBOUR b7 a5)
    (NEIGHBOUR b7 d6)
    (NEIGHBOUR b7 d8)
    (NEIGHBOUR b7 c5)
    (NEIGHBOUR c7 a6)
    (NEIGHBOUR c7 a8)
    (NEIGHBOUR c7 b5)
    (NEIGHBOUR c7 e6)
    (NEIGHBOUR c7 e8)
    (NEIGHBOUR c7 d5)
    (NEIGHBOUR d7 b6)
    (NEIGHBOUR d7 b8)
    (NEIGHBOUR d7 c5)
    (NEIGHBOUR d7 f6)
    (NEIGHBOUR d7 f8)
    (NEIGHBOUR d7 e5)
    (NEIGHBOUR e7 c6)
    (NEIGHBOUR e7 c8)
    (NEIGHBOUR e7 d5)
    (NEIGHBOUR e7 g6)
    (NEIGHBOUR e7 g8)
    (NEIGHBOUR e7 f5)
    (NEIGHBOUR f7 d6)
    (NEIGHBOUR f7 d8)
    (NEIGHBOUR f7 e5)
    (NEIGHBOUR f7 h6)
    (NEIGHBOUR f7 h8)
    (NEIGHBOUR f7 g5)
    (NEIGHBOUR g7 e6)
    (NEIGHBOUR g7 e8)
    (NEIGHBOUR g7 f5)
    (NEIGHBOUR g7 h5)
    (NEIGHBOUR h7 f6)
    (NEIGHBOUR h7 f8)
    (NEIGHBOUR h7 g5)
    (NEIGHBOUR a8 c7)
    (NEIGHBOUR a8 b6)
    (NEIGHBOUR b8 a6)
    (NEIGHBOUR b8 d7)
    (NEIGHBOUR b8 c6)
    (NEIGHBOUR c8 a7)
    (NEIGHBOUR c8 b6)
    (NEIGHBOUR c8 e7)
    (NEIGHBOUR c8 d6)
    (NEIGHBOUR d8 b7)
    (NEIGHBOUR d8 c6)
    (NEIGHBOUR d8 f7)
    (NEIGHBOUR d8 e6)
    (NEIGHBOUR e8 c7)
    (NEIGHBOUR e8 d6)
    (NEIGHBOUR e8 g7)
    (NEIGHBOUR e8 f6)
    (NEIGHBOUR f8 d7)
    (NEIGHBOUR f8 e6)
    (NEIGHBOUR f8 h7)
    (NEIGHBOUR f8 g6)
    (NEIGHBOUR g8 e7)
    (NEIGHBOUR g8 f6)
    (NEIGHBOUR g8 h6)
    (NEIGHBOUR h8 f7)
    (NEIGHBOUR h8 g6)
    (knight-at e1)
    (visited e1)
  )
  (:goal 
    (and
      (visited a1)
      (visited b1)
      (visited c1)
      (visited d1)
      (visited e1)
      (visited f1)
      (visited g1)
      (visited h1)
      (visited a2)
      (visited b2)
      (visited c2)
      (visited d2)
      (visited e2)
      (visited f2)
      (visited g2)
      (visited h2)
      (visited a3)
      (visited b3)
      (visited c3)
      (visited d3)
      (visited e3)
      (visited f3)
      (visited g3)
      (visited h3)
      (visited a4)
      (visited b4)
      (visited c4)
      (visited d4)
      (visited e4)
      (visited f4)
      (visited g4)
      (visited h4)
      (visited a5)
      (visited b5)
      (visited c5)
      (visited d5)
      (visited e5)
      (visited f5)
      (visited g5)
      (visited h5)
      (visited a6)
      (visited b6)
      (visited c6)
      (visited d6)
      (visited e6)
      (visited f6)
      (visited g6)
      (visited h6)
      (visited a7)
      (visited b7)
      (visited c7)
      (visited d7)
      (visited e7)
      (visited f7)
      (visited g7)
      (visited h7)
      (visited a8)
      (visited b8)
      (visited c8)
      (visited d8)
      (visited e8)
      (visited f8)
      (visited g8)
      (visited h8)
    )
  )
)
