#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys

from lab.calls.call import Call
from lab.calls.log import driver_log, driver_err

sys.stdout = driver_log
sys.stderr = driver_err

from lab.calls.log import print_, redirects, save_returncode
from lab.calls.log import set_property

# Make sure we're in the run directory.
os.chdir(os.path.dirname(os.path.abspath(__file__)))

set_property('queue', os.environ.get('QUEUE'))


retcode = Call(['../../code-b850cf57c2f2/fast-downward.py', '--validate', '--search-time-limit', '30m', '--search-memory-limit', '2G', 'domain.pddl', 'problem.pddl', '--search', 'astar(lmcut())'], memory_limit=None, name='fast-downward', time_limit=None, **redirects).wait()
save_returncode('fast-downward', retcode)

retcode = Call(['xz', 'output.sas'], memory_limit=None, name='compress-output-sas', time_limit=None, **redirects).wait()
save_returncode('compress-output-sas', retcode)

retcode = Call(['/usr/bin/python', '../../lab-default-parser.py'], memory_limit=None, name='run-lab-default-parser', time_limit=None, **redirects).wait()
save_returncode('run-lab-default-parser', retcode)

retcode = Call(['/usr/bin/python', '../../preprocess_parser.py'], memory_limit=None, name='parse-preprocess', time_limit=None, **redirects).wait()
save_returncode('parse-preprocess', retcode)

retcode = Call(['/usr/bin/python', '../../search_parser.py'], memory_limit=None, name='parse-search', time_limit=None, **redirects).wait()
save_returncode('parse-search', retcode)


for stream in redirects.values():
    stream.close()
